---
name: check_on_linux_development
on:
  push:
    branches:
      - development_kewl_future

jobs:
  check_development:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - bionic
          - focal
          - jammy
          - noble
          - plucky
          - questing
    steps:
      - uses: actions/checkout@v5
        with:
          ref: development_kewl_future
      - run: sudo apt-get update
      - run: sudo apt-get install libcrypt-dev meson
      - name: Prepare
        run: meson linux_build
      - name: Run tests
        run: meson test -C linux_build --verbose
      - name: Print log on failure
        run: cat linux_build/meson-logs/testlog.txt
