---
name: check_on_macos
on:
  push:
    branches:
      - master

env:
  PKG_CONFIG_PATH: "/opt/homebrew/opt/libxcrypt/lib/pkgconfig"

jobs:
  check_master:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - run: brew install libxcrypt
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          check-latest: true
      - name: Build and install wheel
        env:
          PKG_CONFIG_PATH: "/opt/homebrew/opt/libxcrypt/lib/pkgconfig"
        run: pip install .
      - name: Run tests
        run: python3 -m unittest discover -s tests -v
  check_pypi:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          check-latest: true
      - run: brew install libxcrypt
      - name: Install from pypi
        env:
          PKG_CONFIG_PATH: "/opt/homebrew/opt/libxcrypt/lib/pkgconfig"
        run: pip install pyxcrypt
      - name: Run tests
        run: python3 -m unittest discover -s tests -v
