---
name: check_on_linux_master
on:
  push:
    branches:
      - master

jobs:
  check_master:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - bionic
          - focal
          - jammy
          - noble
          - plucky
          - questing
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libcrypt-dev
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          check-latest: true
      - name: Build and install wheel
        run: pip install .
      - name: Run tests
        run: python3 -m unittest discover -s tests/ -v
  check_pypi:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - bionic
          - focal
          - jammy
          - noble
          - plucky
          - questing
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libcrypt-dev
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          check-latest: true
      - name: Build and install wheel
        run: pip3 install pyxcrypt
      - name: Run tests
        run: python3 -m unittest discover -s tests/ -v
